/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'audio-media': AudioMedia;
    churches: Church;
    'church-branding': ChurchBranding;
    'church-profiles': ChurchProfile;
    events: Event;
    rooms: Room;
    members: Member;
    'service-plans': ServicePlan;
    sermons: Sermon;
    invitations: Invitation;
    groups: Group;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'audio-media': AudioMediaSelect<false> | AudioMediaSelect<true>;
    churches: ChurchesSelect<false> | ChurchesSelect<true>;
    'church-branding': ChurchBrandingSelect<false> | ChurchBrandingSelect<true>;
    'church-profiles': ChurchProfilesSelect<false> | ChurchProfilesSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    rooms: RoomsSelect<false> | RoomsSelect<true>;
    members: MembersSelect<false> | MembersSelect<true>;
    'service-plans': ServicePlansSelect<false> | ServicePlansSelect<true>;
    sermons: SermonsSelect<false> | SermonsSelect<true>;
    invitations: InvitationsSelect<false> | InvitationsSelect<true>;
    groups: GroupsSelect<false> | GroupsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  role: 'super-admin' | 'admin-church' | 'volunteer';
  lastLogin?: string | null;
  tenants?:
    | {
        tenant: number | Church;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "churches".
 */
export interface Church {
  id: number;
  name: string;
  /**
   * Identifiant URL unique (ex: eglise-spotlight)
   */
  slug: string;
  /**
   * Domaine personnalisé pour ce tenant (ex: mon-eglise.fr)
   */
  domain?: string | null;
  /**
   * Lien public en lecture seule du planning. Généré/révoqué depuis le dashboard.
   */
  planningShareToken?: string | null;
  settings?: {
    enabledModules?: 'events'[] | null;
    /**
     * Rôles assignables dans les plannings de culte (présidence, louange, etc.)
     */
    serviceRoles?:
      | {
          label: string;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  church?: (number | null) | Church;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audio-media".
 */
export interface AudioMedia {
  id: number;
  church?: (number | null) | Church;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Charte graphique : logo, favicon et couleurs
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "church-branding".
 */
export interface ChurchBranding {
  id: number;
  church?: (number | null) | Church;
  /**
   * Logo principal (PNG/SVG, fond transparent, min 200×60)
   */
  logo?: (number | null) | Media;
  /**
   * Icône carrée pour l'onglet navigateur (PNG/SVG, 192×192 recommandé)
   */
  favicon?: (number | null) | Media;
  colors?: {
    /**
     * Boutons, liens, accents (ex: #1a73e8)
     */
    primary?: string | null;
    /**
     * Fonds secondaires, hover (ex: #e8e0f8)
     */
    secondary?: string | null;
    /**
     * Highlights, CTA (ex: #FCCA46). Défaut : Sunglow
     */
    accent?: string | null;
    /**
     * Texte principal (ex: #1e2952). Défaut : Raisin
     */
    foreground?: string | null;
    /**
     * Fond de page (ex: #f4f0ec). Défaut : Cream
     */
    background?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Contenu public : présentation, horaires, contact
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "church-profiles".
 */
export interface ChurchProfile {
  id: number;
  church?: (number | null) | Church;
  /**
   * Texte de présentation affiché sur la page « À propos » (2-3 paragraphes)
   */
  description?: string | null;
  address?: {
    street?: string | null;
    postalCode?: string | null;
    city?: string | null;
  };
  contact?: {
    email?: string | null;
    /**
     * Ex: 01 23 45 67 89
     */
    phone?: string | null;
    /**
     * URL complète (ex: https://exemple.com)
     */
    website?: string | null;
  };
  /**
   * Cultes réguliers (dimanche matin, jeudi soir, etc.)
   */
  services?:
    | {
        /**
         * Ex: Culte dominical, Prière du jeudi
         */
        label: string;
        day: 'monday' | 'tuesday' | 'wednesday' | 'thursday' | 'friday' | 'saturday' | 'sunday';
        /**
         * Format 24h (ex: 10:30)
         */
        time: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Informations pour les nouveaux visiteurs
   */
  visitInfo?: {
    duration?: string | null;
    /**
     * Décrivez le déroulement type du culte (louange, prédication, etc.)
     */
    serviceFlow?: string | null;
    /**
     * Garderie, école du dimanche, tranches d'âge, etc.
     */
    childrenInfo?: string | null;
    parking?: string | null;
  };
  /**
   * FAQ affichée sur la page « Première visite »
   */
  faq?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  denomination?: string | null;
  /**
   * Points de foi affichés sur la page publique
   */
  beliefs?:
    | {
        title: string;
        content: string;
        id?: string | null;
      }[]
    | null;
  social?: {
    facebook?: string | null;
    instagram?: string | null;
    youtube?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  title: string;
  date: string;
  time: string;
  /**
   * Salle utilisée pour cet événement (optionnel)
   */
  room?: (number | null) | Room;
  /**
   * Lieu extérieur (si pas de salle sélectionnée)
   */
  location?: string | null;
  description?: string | null;
  /**
   * Image optionnelle pour illustrer l'événement
   */
  image?: (number | null) | Media;
  visibility: 'public' | 'internal';
  /**
   * Auto-assigné au créateur
   */
  createdBy?: (number | null) | User;
  /**
   * Auto-assigné à votre église
   */
  church?: (number | null) | Church;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rooms".
 */
export interface Room {
  id: number;
  name: string;
  capacity?: number | null;
  floor?: string | null;
  description?: string | null;
  equipment?: ('projector' | 'sound' | 'piano' | 'wifi' | 'kitchen' | 'board')[] | null;
  image?: (number | null) | Media;
  accessibility?: boolean | null;
  isActive?: boolean | null;
  /**
   * Auto-assigné au créateur
   */
  createdBy?: (number | null) | User;
  /**
   * Auto-assigné à votre église
   */
  church?: (number | null) | Church;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "members".
 */
export interface Member {
  id: number;
  firstName: string;
  lastName: string;
  email?: string | null;
  phone?: string | null;
  churchRole?: ('pasteur' | 'diacre' | 'ancien' | 'responsable' | 'membre' | 'visiteur') | null;
  birthDate?: string | null;
  photo?: (number | null) | Media;
  /**
   * Lier ce membre à un compte utilisateur Narthex (optionnel)
   */
  user?: (number | null) | User;
  /**
   * Auto-assigné au créateur
   */
  createdBy?: (number | null) | User;
  /**
   * Auto-assigné à votre église
   */
  church?: (number | null) | Church;
  updatedAt: string;
  createdAt: string;
}
/**
 * Plannings de culte : qui fait quoi chaque dimanche
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service-plans".
 */
export interface ServicePlan {
  id: number;
  date: string;
  /**
   * Assignez des membres à chaque rôle pour ce culte
   */
  assignments?:
    | {
        /**
         * Ex : Présidence, Louange, Sono...
         */
        role: string;
        members?: (number | Member)[] | null;
        /**
         * Pour les rôles servis par un groupe entier (ex : Louange)
         */
        group?: (number | null) | Group;
        id?: string | null;
      }[]
    | null;
  /**
   * Informations complémentaires pour ce dimanche
   */
  notes?: string | null;
  /**
   * Auto-assigné au créateur
   */
  createdBy?: (number | null) | User;
  /**
   * Auto-assigné à votre église
   */
  church?: (number | null) | Church;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "groups".
 */
export interface Group {
  id: number;
  name: string;
  description?: string | null;
  members?: (number | Member)[] | null;
  leader?: (number | null) | Member;
  createdBy?: (number | null) | User;
  church: number | Church;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sermons".
 */
export interface Sermon {
  id: number;
  title: string;
  date: string;
  preacher?: (number | null) | Member;
  /**
   * Nom de la série de prédications (optionnel)
   */
  series?: string | null;
  scripture?: string | null;
  description?: string | null;
  /**
   * MP3 ou autre fichier audio de la prédication
   */
  audioFile?: (number | null) | AudioMedia;
  /**
   * URL YouTube ou autre plateforme vidéo
   */
  videoUrl?: string | null;
  /**
   * Image optionnelle pour illustrer la prédication
   */
  image?: (number | null) | Media;
  visibility: 'public' | 'internal';
  /**
   * Auto-assigné au créateur
   */
  createdBy?: (number | null) | User;
  /**
   * Auto-assigné à votre église
   */
  church?: (number | null) | Church;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "invitations".
 */
export interface Invitation {
  id: number;
  email: string;
  status: 'pending' | 'accepted' | 'expired';
  token: string;
  expiresAt: string;
  invitedBy?: (number | null) | User;
  role: 'volunteer' | 'admin-church';
  firstName?: string | null;
  lastName?: string | null;
  church: number | Church;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'audio-media';
        value: number | AudioMedia;
      } | null)
    | ({
        relationTo: 'churches';
        value: number | Church;
      } | null)
    | ({
        relationTo: 'church-branding';
        value: number | ChurchBranding;
      } | null)
    | ({
        relationTo: 'church-profiles';
        value: number | ChurchProfile;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'rooms';
        value: number | Room;
      } | null)
    | ({
        relationTo: 'members';
        value: number | Member;
      } | null)
    | ({
        relationTo: 'service-plans';
        value: number | ServicePlan;
      } | null)
    | ({
        relationTo: 'sermons';
        value: number | Sermon;
      } | null)
    | ({
        relationTo: 'invitations';
        value: number | Invitation;
      } | null)
    | ({
        relationTo: 'groups';
        value: number | Group;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  lastLogin?: T;
  tenants?:
    | T
    | {
        tenant?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  church?: T;
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "audio-media_select".
 */
export interface AudioMediaSelect<T extends boolean = true> {
  church?: T;
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "churches_select".
 */
export interface ChurchesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  domain?: T;
  planningShareToken?: T;
  settings?:
    | T
    | {
        enabledModules?: T;
        serviceRoles?:
          | T
          | {
              label?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "church-branding_select".
 */
export interface ChurchBrandingSelect<T extends boolean = true> {
  church?: T;
  logo?: T;
  favicon?: T;
  colors?:
    | T
    | {
        primary?: T;
        secondary?: T;
        accent?: T;
        foreground?: T;
        background?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "church-profiles_select".
 */
export interface ChurchProfilesSelect<T extends boolean = true> {
  church?: T;
  description?: T;
  address?:
    | T
    | {
        street?: T;
        postalCode?: T;
        city?: T;
      };
  contact?:
    | T
    | {
        email?: T;
        phone?: T;
        website?: T;
      };
  services?:
    | T
    | {
        label?: T;
        day?: T;
        time?: T;
        id?: T;
      };
  visitInfo?:
    | T
    | {
        duration?: T;
        serviceFlow?: T;
        childrenInfo?: T;
        parking?: T;
      };
  faq?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  denomination?: T;
  beliefs?:
    | T
    | {
        title?: T;
        content?: T;
        id?: T;
      };
  social?:
    | T
    | {
        facebook?: T;
        instagram?: T;
        youtube?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  date?: T;
  time?: T;
  room?: T;
  location?: T;
  description?: T;
  image?: T;
  visibility?: T;
  createdBy?: T;
  church?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rooms_select".
 */
export interface RoomsSelect<T extends boolean = true> {
  name?: T;
  capacity?: T;
  floor?: T;
  description?: T;
  equipment?: T;
  image?: T;
  accessibility?: T;
  isActive?: T;
  createdBy?: T;
  church?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "members_select".
 */
export interface MembersSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  email?: T;
  phone?: T;
  churchRole?: T;
  birthDate?: T;
  photo?: T;
  user?: T;
  createdBy?: T;
  church?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service-plans_select".
 */
export interface ServicePlansSelect<T extends boolean = true> {
  date?: T;
  assignments?:
    | T
    | {
        role?: T;
        members?: T;
        group?: T;
        id?: T;
      };
  notes?: T;
  createdBy?: T;
  church?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sermons_select".
 */
export interface SermonsSelect<T extends boolean = true> {
  title?: T;
  date?: T;
  preacher?: T;
  series?: T;
  scripture?: T;
  description?: T;
  audioFile?: T;
  videoUrl?: T;
  image?: T;
  visibility?: T;
  createdBy?: T;
  church?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "invitations_select".
 */
export interface InvitationsSelect<T extends boolean = true> {
  email?: T;
  status?: T;
  token?: T;
  expiresAt?: T;
  invitedBy?: T;
  role?: T;
  firstName?: T;
  lastName?: T;
  church?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "groups_select".
 */
export interface GroupsSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  members?: T;
  leader?: T;
  createdBy?: T;
  church?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}